name: hack_mobility
description: Reducing you mobility CO2 footprint.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
  cloud_firestore: ^0.12.7
  cloud_functions: ^0.4.0+2
  firebase_analytics: ^4.0.1
  firebase_core: ^0.4.0+7
  firebase_storage: ^3.0.3
  google_maps_flutter: ^0.5.19+2
  scoped_model: ^1.0.1
  flutter_typeahead: ^1.6.1
  http: ^0.12.0+2
  firebase_performance: ^0.3.0+3
  location: ^2.3.5
  url_launcher: ^5.1.0
  charts_flutter: ^0.6.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

flutter_icons:
  image_path: "icon/icon.png" 
  android: "launcher_icon" 
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/uber.png
    - assets/jump.png

  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf