/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData flash_on = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData battery_charging_full = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData attach_money = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData globe = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData local_gas_station = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData directions_bus = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cab = const IconData(0xf1b9, fontFamily: _kFontFam);
  static const IconData bicycle = const IconData(0xf206, fontFamily: _kFontFam);
}
